### ISSUE TITLE
Installation with Composer and Typo3 10.4

### ISSUE THREAD

**Issue by tbnobody** [zeichensatz/wok_gpxviewer#2]
I just tried to install the addon using composer. I added the git repository to the repositories section and added the extension to the requirements section:
```
{
        "repositories": [
                { "type": "vcs", "url": "https://github.com/zeichensatz/wok_gpxviewer.git" }
        ],
        "require": {
                "typo3/minimal": "^10.4",
                "wok/wok_gpxviewer": "dev-master"    
        },
}
```

Than I ran `composer.phar upgrade -W --dry-run` and got a lot of dependency errors.

It seems that the composer.json file is limiting the supported Typo3 version to version 8.x.x
https://github.com/zeichensatz/wok_gpxviewer/blob/a1025e881c2dd12171b8a973608bcbfcc017a468/composer.json#L7

I think it should be something like 
`"typo3/cms-core": "^8.7.1 || ^9.5 || ^10.4"`

**Comment by zeichensatz** [comment]
Thanks for pointing me to this issue. Since I don't use composer, I never tested this.
I changed the composer.json as you suggested. Can you please check, if it works now?

**Comment by tbnobody** [comment]
Just tested it (latest LTS 10 version)... it works perfectly now!!
