### ISSUE TITLE
Missing extension-key in composer.json

### ISSUE THREAD

**Issue by tbnobody** [zeichensatz/wok_gpxviewer#3]
Currently my Typo3 instance shows an warning that one extension has no extension key set:
![image](https://user-images.githubusercontent.com/1753222/135152768-8d789d2f-cf6b-40da-937d-280c96ce1ed9.png)

I think this can be fixed by adding something like this to the composer.json file:

```
    "extra": {
        "typo3/cms": {
            "extension-key": "wok_gpxviewer"
        }
    },
```

**Comment by zeichensatz** [comment]
I changed the composer.json accordingly. Hope that works?

Perhaps you can help me with the composer installation?
I tried a composer installation of TYPO3 myself.
I installed TYPO3 with composer as follows:

```
composer create-project "typo3/cms-base-distribution:^10.4" mytest
php vendor/bin/typo3cms install:setup
```

I then added the following lines to the composer.json in the directory `mytest`:
```
        "repositories": [
                {
                        "type": "vcs",
                        "url": "https://github.com/zeichensatz/wok_gpxviewer.git"
                }
        ]
```
But I failed with a correct command to install the extension from the command line.

How did you install the extension in your TYPO3 composer installation?
