### ISSUE TITLE
bootstrap_package works only in version ^11.0 not ^12.0

### ISSUE THREAD

**Issue by tbnobody** [zeichensatz/wok_gpxviewer#4]
During the upgrade from boostrap_package 11 to 12 the path of the bootstrap theme.scss file changed.
Therefore this import fails: https://github.com/zeichensatz/wok_gpxviewer/blob/dc2341dffef5bcdb75b8103b54ee7d8700800aca/Resources/Public/Scss/Theme/theme.scss#L9

To make it compatible with bootstrap_package 12 I had to replace this line with the following:
`@import "../../../../../bootstrap_package/Resources/Public/Scss/bootstrap4/theme";`

But this is a rather ugly way as it makes the extension incompatible with bootstrap_package 11.

Maybe you know a more elegant way?

**Comment by zeichensatz** [comment]
Thanks for pointing this out to me.
I still use `bootstrap_package 11.0.2` but will update next week most probably.

As a solution for the issue described by you, I made the path to the bootstrap_package theme file configurable. For this I did invent a new constant **$gpxviewer-theme** in `GPXVIEWER:BASIC` in the section `Scss Layout Settings`. You may set the constant `plugin.bootstrap_package.settings.scss.gpxviewer-theme` there by a dropdown menu or somewhere in your template(s) with any value (by `plugin.bootstrap_package.settings.scss.gpxviewer-theme=YOURVALUE`).

The dropdown selection offers three values
- `../../../../../bootstrap_package/Resources/Public/Scss/Theme/theme` for Bootstrap package version 11.x
- `../../../../../bootstrap_package/Resources/Public/Scss/bootstrap4/theme` for Bootstrap package version 12.x with bootstrap version 4
- `../../../../../bootstrap_package/Resources/Public/Scss/bootstrap5/theme` for Bootstrap package version 12.x with bootstrap version 5

When taking a short glance into Bootstrap Package 12, I realized, that two bootstrap versions (4 and 5) are supported. Version 5 is set as default in the Bootstrap Package. The options for Bootstrap package 12.x are not tested yet.

The changes are in included in the new branch GPXViewerUpdate, which already includes the update to GPXViewer6.14.

**Comment by zeichensatz** [comment]
Hope, I did solve the problem finally.
Please check if it works for you now.

**Comment by zeichensatz** [comment]
In the meantime I checked the functionality of the constant `plugin.bootstrap_package.settings.scss.gpxviewer-theme` with the branch GPXViewerUpdate with bootstrap_package version 12.0.3 and bootstrap versions 4 and 5 and it did work.
Since I've updated my test installation to bootstrap_package 12.0.3, I did set the default for `plugin.bootstrap_package.settings.scss.gpxviewer-theme` to bootstrap_package 12.0.3 with bootstrap5 (as it is in the bootstrap_package).

**Comment by tbnobody** [comment]
Not sure what I am doing wrong, but I don't see the new setting (gpxviewer-theme) in the Konstanten-Editor...
Already cleared the caches.

**Comment by tbnobody** [comment]
After several tests I figured out, that it seems to be my theme extension which makes some crazy thing. Need some time to check this

**Comment by tbnobody** [comment]
Its working perfectly!!

**Comment by zeichensatz** [comment]
Thanks for testing! I'm happy, it works for you too!
I'm closing this issue now.
